/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jatx_remotekeyboard_windaemon_NativeWrapper */

#ifndef _Included_jatx_remotekeyboard_windaemon_NativeWrapper
#define _Included_jatx_remotekeyboard_windaemon_NativeWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jatx_remotekeyboard_windaemon_NativeWrapper
 * Method:    pressKey
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jatx_remotekeyboard_windaemon_NativeWrapper_pressKey
  (JNIEnv *, jclass, jint);

/*
 * Class:     jatx_remotekeyboard_windaemon_NativeWrapper
 * Method:    releaseKey
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jatx_remotekeyboard_windaemon_NativeWrapper_releaseKey
  (JNIEnv *, jclass, jint);

/*
 * Class:     jatx_remotekeyboard_windaemon_NativeWrapper
 * Method:    setRusLang
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jatx_remotekeyboard_windaemon_NativeWrapper_setRusLang
  (JNIEnv *, jclass);

/*
 * Class:     jatx_remotekeyboard_windaemon_NativeWrapper
 * Method:    setEngLang
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jatx_remotekeyboard_windaemon_NativeWrapper_setEngLang
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
